image: alpine/edge
triggers:
  - action: email
    condition: failure
    to: srhtbuilds@k6.tel
environment:
  repo: bttj-millennium-edition
secrets:
  - 353c736b-4578-44a7-8152-d15225996d33
tasks:
  - mirror_to_github: |
      cd ~/$repo
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      git remote add github git@github.com:amdaith/$repo.git
      git push github main
      git switch original-files
      git push github original-files

